# Generated by Django 2.1.2 on 2018-10-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('encargado', models.CharField(max_length=30)),
                ('sena', models.IntegerField()),
                ('fecha_sena', models.DateField()),
                ('vencimiento', models.DateField()),
                ('precio', models.FloatField()),
                ('nombre_solicitante', models.CharField(max_length=40)),
                ('nombre_cumpleanero', models.CharField(max_length=40)),
                ('observaciones', models.TextField()),
                ('adicionales', models.ManyToManyField(blank=True, to='myApp.Adicional')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, null=True)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='sucursal',
            field=models.ForeignKey(on_delete=False, to='myApp.Sucursal'),
        ),
    ]
