# Generated by Django 2.1.2 on 2018-10-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id_combo', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='combo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.Combo'),
        ),
    ]
