# Generated by Django 2.1.2 on 2018-10-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_auto_20181028_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='adicionales',
            field=models.ManyToManyField(blank=True, null=True, to='myApp.Adicional'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='vencimiento',
            field=models.DateField(null=True),
        ),
    ]
